using FisCompendium.Web.Models.MapData;
using Microsoft.AspNetCore.Mvc;

namespace FisCompendium.Web.Controllers
{
    public class MapController : Controller
    {
        public IActionResult Error()
        {
            return View();
        }

        public IActionResult Local()
        {
            return View();
        }

        public IActionResult DamageReport()
        {
            var damageReport = new HexHealth[]
            {
                new HexHealth { X=10, Y=25, Health=2 },
                new HexHealth { X=9, Y=25, Health=2 },
                new HexHealth { X=8, Y=25, Health=2 },
                new HexHealth { X=8, Y=24, Health=3 },
                new HexHealth { X=9, Y=24, Health=2 },
                new HexHealth { X=10, Y=24, Health=1 },
                new HexHealth { X=11, Y=24, Health=1 },
                new HexHealth { X=12, Y=23, Health=3 },
                new HexHealth { X=11, Y=23, Health=1 },
                new HexHealth { X=8, Y=23, Health=2 },
                new HexHealth { X=7, Y=23, Health=3 },
                new HexHealth { X=7, Y=22, Health=3 },
                new HexHealth { X=10, Y=22, Health=2 },
                new HexHealth { X=11, Y=22, Health=1 },
                new HexHealth { X=12, Y=21, Health=1 },
                new HexHealth { X=10, Y=21, Health=1 },
                new HexHealth { X=9, Y=21, Health=1 },
                new HexHealth { X=8, Y=21, Health=1 },
                new HexHealth { X=7, Y=21, Health=2 },
                new HexHealth { X=10, Y=20, Health=3 },
                new HexHealth { X=11, Y=20, Health=3 },
                new HexHealth { X=12, Y=20, Health=3 },
                new HexHealth { X=11, Y=19, Health=1 },
                new HexHealth { X=10, Y=19, Health=1 },
                new HexHealth { X=9, Y=19, Health=2 },
                new HexHealth { X=8, Y=19, Health=2 },
                new HexHealth { X=10, Y=18, Health=1 },
                new HexHealth { X=8, Y=17, Health=2 },
                new HexHealth { X=6, Y=19, Health=1 },
                new HexHealth { X=7, Y=18, Health=1 },
                new HexHealth { X=7, Y=17, Health=3 },
                new HexHealth { X=8, Y=16, Health=1 },
                new HexHealth { X=8, Y=15, Health=3 },
                new HexHealth { X=9, Y=13, Health=3 },
                new HexHealth { X=10, Y=12, Health=2 },
                new HexHealth { X=9, Y=12, Health=2 },
                new HexHealth { X=8, Y=13, Health=3 },
                new HexHealth { X=8, Y=14, Health=2 },
                new HexHealth { X=7, Y=15, Health=3 },
                new HexHealth { X=7, Y=16, Health=3 },
                new HexHealth { X=6, Y=17, Health=3 },
                new HexHealth { X=6, Y=18, Health=3 },
                new HexHealth { X=5, Y=18, Health=3 },
                new HexHealth { X=5, Y=17, Health=2 },
                new HexHealth { X=6, Y=16, Health=2 },
                new HexHealth { X=6, Y=15, Health=3 },
                new HexHealth { X=7, Y=14, Health=3 },
                new HexHealth { X=7, Y=13, Health=1 },
                new HexHealth { X=8, Y=12, Health=3 },
                new HexHealth { X=7, Y=11, Health=3 },
                new HexHealth { X=7, Y=12, Health=3 },
                new HexHealth { X=6, Y=13, Health=1 },
                new HexHealth { X=5, Y=16, Health=1 },
                new HexHealth { X=4, Y=17, Health=3 },
                new HexHealth { X=4, Y=18, Health=3 },
                new HexHealth { X=3, Y=17, Health=2 },
                new HexHealth { X=4, Y=16, Health=3 },
                new HexHealth { X=4, Y=15, Health=3 },
                new HexHealth { X=4, Y=14, Health=3 },
                new HexHealth { X=3, Y=15, Health=3 },
                new HexHealth { X=3, Y=16, Health=3 },
                new HexHealth { X=2, Y=17, Health=1 },
                new HexHealth { X=1, Y=17, Health=2 },
                new HexHealth { X=2, Y=16, Health=1 },
                new HexHealth { X=2, Y=15, Health=3 },
                new HexHealth { X=3, Y=14, Health=1 },
                new HexHealth { X=2, Y=14, Health=3 },
                new HexHealth { X=1, Y=15, Health=1 },
                new HexHealth { X=1, Y=16, Health=2 },
                new HexHealth { X=0, Y=15, Health=2 },
                new HexHealth { X=1, Y=14, Health=2 },
                new HexHealth { X=11, Y=14, Health=2 },
                new HexHealth { X=11, Y=15, Health=3 },
                new HexHealth { X=12, Y=15, Health=3 },
                new HexHealth { X=13, Y=16, Health=2 },
                new HexHealth { X=13, Y=15, Health=3 },
                new HexHealth { X=14, Y=16, Health=3 },
                new HexHealth { X=5, Y=13, Health=2 },
                new HexHealth { X=4, Y=13, Health=3 },
                new HexHealth { X=3, Y=13, Health=3 },
                new HexHealth { X=2, Y=13, Health=2 },
                new HexHealth { X=1, Y=13, Health=3 },
                new HexHealth { X=1, Y=12, Health=3 },
                new HexHealth { X=2, Y=12, Health=3 },
                new HexHealth { X=3, Y=12, Health=3 },
                new HexHealth { X=4, Y=12, Health=3 },
                new HexHealth { X=5, Y=12, Health=3 },
                new HexHealth { X=5, Y=11, Health=3 },
                new HexHealth { X=4, Y=11, Health=3 },
                new HexHealth { X=3, Y=11, Health=3 },
                new HexHealth { X=2, Y=11, Health=2 },
                new HexHealth { X=1, Y=11, Health=3 },
                new HexHealth { X=0, Y=11, Health=3 },
                new HexHealth { X=0, Y=10, Health=3 },
                new HexHealth { X=1, Y=10, Health=3 },
                new HexHealth { X=2, Y=10, Health=3 },
                new HexHealth { X=3, Y=10, Health=3 },
                new HexHealth { X=4, Y=10, Health=3 },
                new HexHealth { X=5, Y=10, Health=3 },
                new HexHealth { X=4, Y=9, Health=3 },
                new HexHealth { X=3, Y=9, Health=3 },
                new HexHealth { X=2, Y=9, Health=3 },
                new HexHealth { X=1, Y=9, Health=3 },
                new HexHealth { X=0, Y=9, Health=3 },
                new HexHealth { X=1, Y=8, Health=3 },
                new HexHealth { X=2, Y=8, Health=3 },
                new HexHealth { X=3, Y=8, Health=2 },
                new HexHealth { X=4, Y=8, Health=2 },
                new HexHealth { X=5, Y=8, Health=3 },
                new HexHealth { X=4, Y=7, Health=3 },
                new HexHealth { X=3, Y=7, Health=3 },
                new HexHealth { X=2, Y=7, Health=3 },
                new HexHealth { X=2, Y=6, Health=3 },
                new HexHealth { X=3, Y=6, Health=3 },
                new HexHealth { X=3, Y=5, Health=3 },
                new HexHealth { X=4, Y=6, Health=3 },
                new HexHealth { X=4, Y=5, Health=3 },
                new HexHealth { X=9, Y=27, Health=0 },
                new HexHealth { X=10, Y=27, Health=0 },
                new HexHealth { X=10, Y=26, Health=0 },
                new HexHealth { X=11, Y=26, Health=0 },
                new HexHealth { X=11, Y=25, Health=0 },
                new HexHealth { X=12, Y=24, Health=0 },
                new HexHealth { X=13, Y=22, Health=0 },
                new HexHealth { X=9, Y=18, Health=0 },
                new HexHealth { X=10, Y=17, Health=0 },
                new HexHealth { X=9, Y=17, Health=0 },
                new HexHealth { X=10, Y=16, Health=0 },
                new HexHealth { X=9, Y=15, Health=0 },
                new HexHealth { X=9, Y=16, Health=0 },
                new HexHealth { X=5, Y=19, Health=0 },
                new HexHealth { X=6, Y=14, Health=0 },
                new HexHealth { X=5, Y=15, Health=0 },
                new HexHealth { X=10, Y=15, Health=0 },
                new HexHealth { X=10, Y=14, Health=0 },
                new HexHealth { X=10, Y=23, Health=0 },
                new HexHealth { X=8, Y=18, Health=0 },
                new HexHealth { X=9, Y=23, Health=0 },
                new HexHealth { X=8, Y=22, Health=0 },
                new HexHealth { X=9, Y=22, Health=0 },
                new HexHealth { X=12, Y=22, Health=0 },
                new HexHealth { X=13, Y=21, Health=0 },
                new HexHealth { X=11, Y=21, Health=0 },
                new HexHealth { X=8, Y=20, Health=0 },
                new HexHealth { X=9, Y=20, Health=0 },
                new HexHealth { X=7, Y=19, Health=0 },
                new HexHealth { X=9, Y=14, Health=0 },
                new HexHealth { X=10, Y=13, Health=0 },
                new HexHealth { X=3, Y=18, Health=0 },
                new HexHealth { X=5, Y=14, Health=0 },

            };

            return View(damageReport);
        }

        public IActionResult World()
        {
            return View();
        }
    }
}
